# Generated by Django 3.2.22 on 2023-10-18 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OffreEmploi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('intitule', models.TextField()),
                ('description', models.TextField()),
                ('dateCreation', models.TextField()),
                ('dateActualisation', models.TextField()),
                ('lieuTravail', models.TextField()),
                ('romeCode', models.TextField()),
                ('romeLibelle', models.TextField()),
                ('appellationlibelle', models.TextField()),
                ('entreprise', models.TextField()),
                ('typeContrat', models.TextField()),
                ('typeContratLibelle', models.TextField()),
                ('natureContrat', models.TextField()),
                ('experienceExige', models.BooleanField(null=True)),
                ('experienceLibelle', models.TextField()),
                ('experienceCommentaire', models.TextField()),
                ('formations', models.TextField()),
                ('competences', models.TextField()),
                ('salaire', models.TextField()),
                ('dureeTravailLibelle', models.TextField()),
                ('dureeTravailLibelleConverti', models.TextField()),
                ('alternance', models.BooleanField(null=True)),
                ('contact', models.TextField()),
                ('agence', models.TextField()),
                ('nombrePostes', models.BigIntegerField(null=True)),
                ('accessibleTH', models.BooleanField(null=True)),
                ('qualificationCode', models.BigIntegerField(null=True)),
                ('qualificationLibelle', models.TextField()),
                ('codeNAF', models.TextField()),
                ('secteurActivite', models.BigIntegerField(null=True)),
                ('secteurActiviteLibelle', models.TextField()),
                ('qualitesProfessionnelles', models.TextField()),
                ('origineOffre', models.TextField()),
                ('deplacementCode', models.FloatField(null=True)),
                ('deplacementLibelle', models.TextField()),
                ('offresManqueCandidats', models.BooleanField(null=True)),
                ('complementExercice', models.TextField()),
                ('permis', models.TextField()),
                ('langues', models.TextField()),
                ('conditionExercice', models.TextField()),
            ],
            options={
                'db_table': 'offres_emplois',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1000)),
                ('entreprise', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lieu', models.CharField(max_length=100)),
                ('type_contrat', models.CharField(max_length=5)),
                ('experience', models.CharField(max_length=100)),
                ('exigences', models.TextField()),
                ('qualification', models.CharField(max_length=100)),
                ('qualites_pro', models.TextField()),
                ('formations', models.CharField(max_length=100)),
                ('langues', models.CharField(max_length=100)),
                ('salaire', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('experiences', models.TextField(blank=True, max_length=1000)),
                ('formations', models.TextField(blank=True, max_length=1000)),
                ('metiers_recherches', models.CharField(blank=True, max_length=100)),
                ('compte_linkedin', models.URLField(blank=True)),
                ('compte_twitter', models.CharField(blank=True, max_length=100)),
                ('compte_github', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
